//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Urmah.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Urmah.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {0}.
        /// </summary>
        internal static string AboutTitleFormatString {
            get {
                return ResourceManager.GetString("AboutTitleFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: .
        /// </summary>
        internal static string CaptationFormatString {
            get {
                return ResourceManager.GetString("CaptationFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new role.
        /// </summary>
        internal static string CreateRole {
            get {
                return ResourceManager.GetString("CreateRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new user.
        /// </summary>
        internal static string CreateUser {
            get {
                return ResourceManager.GetString("CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing roles: {0}.
        /// </summary>
        internal static string ExistingRolesFormatString {
            get {
                return ResourceManager.GetString("ExistingRolesFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing users: {0}.
        /// </summary>
        internal static string ExistingUsersFormatString {
            get {
                return ResourceManager.GetString("ExistingUsersFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online users: {1} / {0}.
        /// </summary>
        internal static string ExistingUsersOnlineTotalRation {
            get {
                return ResourceManager.GetString("ExistingUsersOnlineTotalRation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        internal static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage roles.
        /// </summary>
        internal static string ManageRoles {
            get {
                return ResourceManager.GetString("ManageRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage users.
        /// </summary>
        internal static string ManageUsers {
            get {
                return ResourceManager.GetString("ManageUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership problem: {0}.
        /// </summary>
        internal static string MembershipExceptionMessage {
            get {
                return ResourceManager.GetString("MembershipExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to offline.
        /// </summary>
        internal static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to online.
        /// </summary>
        internal static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next {0}.
        /// </summary>
        internal static string PagingNextFormatString {
            get {
                return ResourceManager.GetString("PagingNextFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to role.
        /// </summary>
        internal static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Browser for {0} on {1}.
        /// </summary>
        internal static string RoleBrowserTitleFormatString {
            get {
                return ResourceManager.GetString("RoleBrowserTitleFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role problem: {0}.
        /// </summary>
        internal static string RoleExceptionMessage {
            get {
                return ResourceManager.GetString("RoleExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role management is disabled for this application..
        /// </summary>
        internal static string RoleManagementDisabled {
            get {
                return ResourceManager.GetString("RoleManagementDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to roles.
        /// </summary>
        internal static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details&amp;hellip;.
        /// </summary>
        internal static string RolesActionDetail {
            get {
                return ResourceManager.GetString("RolesActionDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage existing roles.
        /// </summary>
        internal static string RolesLinkDescription {
            get {
                return ResourceManager.GetString("RolesLinkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} roles found..
        /// </summary>
        internal static string RolesPagingStats {
            get {
                return ResourceManager.GetString("RolesPagingStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        internal static string RolesTitle {
            get {
                return ResourceManager.GetString("RolesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users and Roles for {0} on {1}.
        /// </summary>
        internal static string TitleFormatString {
            get {
                return ResourceManager.GetString("TitleFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        internal static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User account is locked out..
        /// </summary>
        internal static string UserAccountLockedOut {
            get {
                return ResourceManager.GetString("UserAccountLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User account is not locked out (that&apos;s a good thing).
        /// </summary>
        internal static string UserAccountNotLockedOut {
            get {
                return ResourceManager.GetString("UserAccountNotLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Browser for {0} on {1}.
        /// </summary>
        internal static string UserBrowserTitleFormatString {
            get {
                return ResourceManager.GetString("UserBrowserTitleFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Information.
        /// </summary>
        internal static string UserCreateBasicBoxTitle {
            get {
                return ResourceManager.GetString("UserCreateBasicBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Further Information (optional).
        /// </summary>
        internal static string UserCreateFurtherBoxTitle {
            get {
                return ResourceManager.GetString("UserCreateFurtherBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User account creation failed: {0}.
        /// </summary>
        internal static string UserCreationFailureFormatString {
            get {
                return ResourceManager.GetString("UserCreationFailureFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User account was successfully created..
        /// </summary>
        internal static string UserCreationSuccess {
            get {
                return ResourceManager.GetString("UserCreationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Information.
        /// </summary>
        internal static string UserDetailAccountInformationTitle {
            get {
                return ResourceManager.GetString("UserDetailAccountInformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved:.
        /// </summary>
        internal static string UserDetailAccountIsApprovedCaption {
            get {
                return ResourceManager.GetString("UserDetailAccountIsApprovedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked out:.
        /// </summary>
        internal static string UserDetailAccountIsLockedOutCaption {
            get {
                return ResourceManager.GetString("UserDetailAccountIsLockedOutCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        internal static string UserDetailApprovedCheckboxCaption {
            get {
                return ResourceManager.GetString("UserDetailApprovedCheckboxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created:.
        /// </summary>
        internal static string UserDetailCreationDateCaption {
            get {
                return ResourceManager.GetString("UserDetailCreationDateCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        internal static string UserDetailEmailCaption {
            get {
                return ResourceManager.GetString("UserDetailEmailCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User status:.
        /// </summary>
        internal static string UserDetailIsOnlineCaption {
            get {
                return ResourceManager.GetString("UserDetailIsOnlineCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Activity:.
        /// </summary>
        internal static string UserDetailLastActivityCaption {
            get {
                return ResourceManager.GetString("UserDetailLastActivityCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Login:.
        /// </summary>
        internal static string UserDetailLastLoginCaption {
            get {
                return ResourceManager.GetString("UserDetailLastLoginCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User: {0}.
        /// </summary>
        internal static string UserDetailPageTitleFormatString {
            get {
                return ResourceManager.GetString("UserDetailPageTitleFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password answer:.
        /// </summary>
        internal static string UserDetailPasswordAnswerCaption {
            get {
                return ResourceManager.GetString("UserDetailPasswordAnswerCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string UserDetailPasswordCaption {
            get {
                return ResourceManager.GetString("UserDetailPasswordCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm:.
        /// </summary>
        internal static string UserDetailPasswordConfirmCaption {
            get {
                return ResourceManager.GetString("UserDetailPasswordConfirmCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password question:.
        /// </summary>
        internal static string UserDetailPasswordQuestionCaption {
            get {
                return ResourceManager.GetString("UserDetailPasswordQuestionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string UserDetailProfileTitle {
            get {
                return ResourceManager.GetString("UserDetailProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        internal static string UserDetailRolesTitle {
            get {
                return ResourceManager.GetString("UserDetailRolesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        internal static string UserDetailTitleFormatString {
            get {
                return ResourceManager.GetString("UserDetailTitleFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock.
        /// </summary>
        internal static string UserDetailUnlock {
            get {
                return ResourceManager.GetString("UserDetailUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        internal static string UserDetailUsernameCaption {
            get {
                return ResourceManager.GetString("UserDetailUsernameCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create User for {0} on {1}.
        /// </summary>
        internal static string UserEditTile_CreateFormatString {
            get {
                return ResourceManager.GetString("UserEditTile_CreateFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add role:.
        /// </summary>
        internal static string UserInRoleAddRoleCaption {
            get {
                return ResourceManager.GetString("UserInRoleAddRoleCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string UserInRoleAddRoleOkButtonCaption {
            get {
                return ResourceManager.GetString("UserInRoleAddRoleOkButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string UserInRoleDelete {
            get {
                return ResourceManager.GetString("UserInRoleDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is offline.
        /// </summary>
        internal static string UserIsOffline {
            get {
                return ResourceManager.GetString("UserIsOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is online.
        /// </summary>
        internal static string UserIsOnline {
            get {
                return ResourceManager.GetString("UserIsOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found in data store..
        /// </summary>
        internal static string UserNotFoundInDataStore {
            get {
                return ResourceManager.GetString("UserNotFoundInDataStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users {0} to {1} of total {2} (page {3} of {4})..
        /// </summary>
        internal static string UserPagingStats {
            get {
                return ResourceManager.GetString("UserPagingStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to users.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details&amp;hellip;.
        /// </summary>
        internal static string UsersActionDetail {
            get {
                return ResourceManager.GetString("UsersActionDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string UserSearchFormSubmitText {
            get {
                return ResourceManager.GetString("UserSearchFormSubmitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name:.
        /// </summary>
        internal static string UserSearchFormUsername {
            get {
                return ResourceManager.GetString("UserSearchFormUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage existing users.
        /// </summary>
        internal static string UsersLinkDescription {
            get {
                return ResourceManager.GetString("UsersLinkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string UsersTitle {
            get {
                return ResourceManager.GetString("UsersTitle", resourceCulture);
            }
        }
    }
}
